"""add relationship and foreign key with supermarket

Revision ID: 4ee2ba7397bf
Revises: de1016a2d2cd
Create Date: 2025-06-19 00:47:45.635336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee2ba7397bf'
down_revision: Union[str, None] = 'de1016a2d2cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_lists', sa.Column('supermarket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shopping_lists', 'supermarkets', ['supermarket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_lists', type_='foreignkey')
    op.drop_column('shopping_lists', 'supermarket_id')
    # ### end Alembic commands ###
