"""exclude step_minute to recipe_step

Revision ID: e8251b8610de
Revises: ea1a33f983c9
Create Date: 2025-06-23 15:18:45.764173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8251b8610de'
down_revision: Union[str, None] = 'ea1a33f983c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_steps', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_steps', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
